import { db } from "./db";

export const seedData = async () => {
  const jobsCount = await db.jobs.count();
  if (jobsCount > 0) return; // already seeded

  const jobs = [
    {
      id: "1",
      title: "Frontend Developer",
      slug: "frontend-developer",
      status: "active",
      requiredSkills: ["React", "JavaScript"],
      preferredSkills: ["TypeScript"],
      salary: "8 LPA",
      location: "Remote",
      workType: "Full-time",
      tags: ["frontend", "react"],
      candidates: 0,
    },
    {
      id: "2",
      title: "Backend Developer",
      slug: "backend-developer",
      status: "active",
      requiredSkills: ["Node.js", "Express"],
      preferredSkills: ["MongoDB"],
      salary: "10 LPA",
      location: "Bangalore",
      workType: "Full-time",
      tags: ["backend", "node"],
      candidates: 0,
    },
    {
      id: "3",
      title: "Fullstack Engineer",
      slug: "fullstack-engineer",
      status: "active",
      requiredSkills: ["React", "Node.js"],
      preferredSkills: ["GraphQL", "AWS"],
      salary: "12 LPA",
      location: "Delhi",
      workType: "Hybrid",
      tags: ["fullstack", "web"],
      candidates: 0,
    },
    {
      id: "4",
      title: "Mobile App Developer",
      slug: "mobile-app-developer",
      status: "active",
      requiredSkills: ["React Native", "JavaScript"],
      preferredSkills: ["Flutter"],
      salary: "9 LPA",
      location: "Mumbai",
      workType: "Full-time",
      tags: ["mobile", "react-native"],
      candidates: 0,
    },
    {
      id: "5",
      title: "DevOps Engineer",
      slug: "devops-engineer",
      status: "active",
      requiredSkills: ["AWS", "Docker"],
      preferredSkills: ["Kubernetes"],
      salary: "11 LPA",
      location: "Remote",
      workType: "Full-time",
      tags: ["devops", "cloud"],
      candidates: 0,
    },
    {
      id: "6",
      title: "Data Scientist",
      slug: "data-scientist",
      status: "active",
      requiredSkills: ["Python", "Machine Learning"],
      preferredSkills: ["Deep Learning"],
      salary: "14 LPA",
      location: "Hyderabad",
      workType: "Full-time",
      tags: ["data", "ml"],
      candidates: 0,
    },
    {
      id: "7",
      title: "Data Engineer",
      slug: "data-engineer",
      status: "active",
      requiredSkills: ["SQL", "ETL"],
      preferredSkills: ["BigQuery", "Spark"],
      salary: "13 LPA",
      location: "Pune",
      workType: "Full-time",
      tags: ["data", "pipeline"],
      candidates: 0,
    },
    {
      id: "8",
      title: "QA Engineer",
      slug: "qa-engineer",
      status: "active",
      requiredSkills: ["Selenium", "JavaScript"],
      preferredSkills: ["Cypress"],
      salary: "7 LPA",
      location: "Chennai",
      workType: "Full-time",
      tags: ["qa", "testing"],
      candidates: 0,
    },
    {
      id: "9",
      title: "UI/UX Designer",
      slug: "ui-ux-designer",
      status: "active",
      requiredSkills: ["Figma", "Adobe XD"],
      preferredSkills: ["Illustrator"],
      salary: "6 LPA",
      location: "Remote",
      workType: "Part-time",
      tags: ["design", "uiux"],
      candidates: 0,
    },
    {
      id: "10",
      title: "System Administrator",
      slug: "system-administrator",
      status: "active",
      requiredSkills: ["Linux", "Networking"],
      preferredSkills: ["Cloud"],
      salary: "8 LPA",
      location: "Bangalore",
      workType: "Full-time",
      tags: ["sysadmin", "infra"],
      candidates: 0,
    },
    {
      id: "11",
      title: "AI Engineer",
      slug: "ai-engineer",
      status: "active",
      requiredSkills: ["Python", "TensorFlow"],
      preferredSkills: ["PyTorch"],
      salary: "15 LPA",
      location: "Delhi",
      workType: "Hybrid",
      tags: ["ai", "ml"],
      candidates: 0,
    },
    {
      id: "12",
      title: "Product Manager",
      slug: "product-manager",
      status: "active",
      requiredSkills: ["Agile", "Scrum"],
      preferredSkills: ["Jira"],
      salary: "18 LPA",
      location: "Remote",
      workType: "Full-time",
      tags: ["pm", "management"],
      candidates: 0,
    },
    {
      id: "13",
      title: "Game Developer",
      slug: "game-developer",
      status: "active",
      requiredSkills: ["Unity", "C#"],
      preferredSkills: ["Blender"],
      salary: "10 LPA",
      location: "Mumbai",
      workType: "Full-time",
      tags: ["game", "unity"],
      candidates: 0,
    },
    {
      id: "14",
      title: "Blockchain Developer",
      slug: "blockchain-developer",
      status: "active",
      requiredSkills: ["Solidity", "Ethereum"],
      preferredSkills: ["Web3.js"],
      salary: "16 LPA",
      location: "Remote",
      workType: "Full-time",
      tags: ["blockchain", "crypto"],
      candidates: 0,
    },
    {
      id: "15",
      title: "Cybersecurity Analyst",
      slug: "cybersecurity-analyst",
      status: "active",
      requiredSkills: ["Security", "Penetration Testing"],
      preferredSkills: ["CEH"],
      salary: "13 LPA",
      location: "Hyderabad",
      workType: "Full-time",
      tags: ["security", "cyber"],
      candidates: 0,
    },
    {
      id: "16",
      title: "Cloud Architect",
      slug: "cloud-architect",
      status: "active",
      requiredSkills: ["AWS", "Azure"],
      preferredSkills: ["GCP"],
      salary: "20 LPA",
      location: "Bangalore",
      workType: "Full-time",
      tags: ["cloud", "infra"],
      candidates: 0,
    },
    {
      id: "17",
      title: "Database Administrator",
      slug: "database-administrator",
      status: "active",
      requiredSkills: ["MySQL", "PostgreSQL"],
      preferredSkills: ["Oracle"],
      salary: "12 LPA",
      location: "Pune",
      workType: "Full-time",
      tags: ["db", "sql"],
      candidates: 0,
    },
    {
      id: "18",
      title: "Technical Writer",
      slug: "technical-writer",
      status: "active",
      requiredSkills: ["Documentation", "Markdown"],
      preferredSkills: ["Confluence"],
      salary: "5 LPA",
      location: "Remote",
      workType: "Part-time",
      tags: ["writer", "docs"],
      candidates: 0,
    },
    {
      id: "19",
      title: "Business Analyst",
      slug: "business-analyst",
      status: "active",
      requiredSkills: ["Excel", "SQL"],
      preferredSkills: ["Power BI"],
      salary: "9 LPA",
      location: "Delhi",
      workType: "Hybrid",
      tags: ["ba", "analysis"],
      candidates: 0,
    },
    {
      id: "20",
      title: "Support Engineer",
      slug: "support-engineer",
      status: "active",
      requiredSkills: ["Customer Support", "Troubleshooting"],
      preferredSkills: ["SaaS"],
      salary: "6 LPA",
      location: "Chennai",
      workType: "Full-time",
      tags: ["support", "tech"],
      candidates: 0,
    },
    {
      id: "21",
      title: "SEO Specialist",
      slug: "seo-specialist",
      status: "active",
      requiredSkills: ["SEO", "Google Analytics"],
      preferredSkills: ["Content Marketing"],
      salary: "7 LPA",
      location: "Remote",
      workType: "Part-time",
      tags: ["seo", "marketing"],
      candidates: 0,
    },
    {
      id: "22",
      title: "Content Writer",
      slug: "content-writer",
      status: "active",
      requiredSkills: ["Writing", "Research"],
      preferredSkills: ["SEO"],
      salary: "5 LPA",
      location: "Mumbai",
      workType: "Full-time",
      tags: ["content", "writing"],
      candidates: 0,
    },
    {
      id: "23",
      title: "HR Manager",
      slug: "hr-manager",
      status: "active",
      requiredSkills: ["Recruitment", "Employee Engagement"],
      preferredSkills: ["Payroll"],
      salary: "8 LPA",
      location: "Delhi",
      workType: "Full-time",
      tags: ["hr", "people"],
      candidates: 0,
    },
    {
      id: "24",
      title: "Sales Executive",
      slug: "sales-executive",
      status: "active",
      requiredSkills: ["Communication", "Negotiation"],
      preferredSkills: ["CRM"],
      salary: "6 LPA",
      location: "Pune",
      workType: "Full-time",
      tags: ["sales", "bizdev"],
      candidates: 0,
    },
    {
      id: "25",
      title: "Operations Manager",
      slug: "operations-manager",
      status: "active",
      requiredSkills: ["Operations", "Leadership"],
      preferredSkills: ["Lean Management"],
      salary: "12 LPA",
      location: "Hyderabad",
      workType: "Full-time",
      tags: ["ops", "management"],
      candidates: 0,
    },
  ];

  for (let job of jobs) {
    await db.jobs.add(job);
  }
};
